### ISSUE TITLE
Test::Version test didn't fail on bad quoted 3-part v-string versions

### ISSUE THREAD

**Issue by doherty** [xenoterracide/Dist-Zilla-Plugin-Test-Version#2]
I released a bunch of modules with `our $VERSION = 'v2.0.0';` - which is apparently Not Good. That shouldn't pass the test.

**Comment by xenoterracide** [comment]
yes it should.... that's valid according to `is_strict` rules... in fact `2.0.0` `is_lax` but is not `is_strict`. unless I'm somehow misunderstanding?

you are welcome to try the unreleased `v1.1.0` of Test::Version and enable strictness (however I did that) to see if it passes `is_strict`, but that should.

**Comment by doherty** [comment]
BAH, I hate version numbers `>.<`
