### ISSUE TITLE
Test::Version should be loaded without Test::Requires

### ISSUE THREAD

**Issue by dolmen** [xenoterracide/Dist-Zilla-Plugin-Test-Version#4]
[lib/Dist/Zilla/Plugin/Test/Version.pm line 116](https://github.com/xenoterracide/Dist-Zilla-Plugin-Test-Version/blob/build/master/lib/Dist/Zilla/Plugin/Test/Version.pm#L116)

In the generated test, the Test::Version module should be loaded unconditionnally instead of using Test::Requires.
This problem is similar to the [RT#76038 on Test::EOL](https://rt.cpan.org/Ticket/Display.html?id=76038#txn-1057838).

**Comment by xenoterracide** [comment]
should be resolved as of 0.002003 let me know if there are any more issues.
